version: '2'

services:
  server:
    image: server:local-build
    build:
      context: "src/server"
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - "./.env.server:/app/.env"
  client:
    image: client:local-build
    build:
      context: "src/client"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./.env.client:/app/build/env.js"