version: '2'

services:
  server:
    image: server:local-build
    build:
      context: "src/server"
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:5000"
    volumes:
      - "./.env.server:/app/.env"
  client:
    image: client:local-build
    build:
      context: "src/client"
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - "./.env.client:/app/build/env.js"